# Form implementation generated from reading ui file 'c:\Users\barba\Documents\vs\Show do Milhão\home.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 373)
        MainWindow.setMinimumSize(QtCore.QSize(1160, 373))
        MainWindow.setMaximumSize(QtCore.QSize(1160, 373))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\Show do Milhão\\imgs/icone.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 1641, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\Show do Milhão\\imgs/home background.png"))
        self.label.setObjectName("label")
        self.botaoJogar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botaoJogar.setGeometry(QtCore.QRect(490, 280, 211, 61))
        self.botaoJogar.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 24pt \"Garamond\";\n"
"color: rgb(255, 255, 0);\n"
"border-radius: 15px;\n"
"border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 5px solid rgb(255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:clicked {\n"
"\n"
"}")
        self.botaoJogar.setObjectName("botaoJogar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Show do Milhão Finances"))
        self.botaoJogar.setText(_translate("MainWindow", "Jogar"))
