# Form implementation generated from reading ui file 'c:\Users\barba\Documents\vs\Show do Milhão\maior pontuacao.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 373)
        MainWindow.setMinimumSize(QtCore.QSize(1160, 373))
        MainWindow.setMaximumSize(QtCore.QSize(1160, 373))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\Show do Milhão\\imgs/icone.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -70, 1311, 511))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\Show do Milhão\\imgs/templante premiação final um milhão.png"))
        self.label.setObjectName("label")
        self.botaoInicio = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botaoInicio.setGeometry(QtCore.QRect(430, 290, 231, 61))
        self.botaoInicio.setStyleSheet("QPushButton{\n"
"font: 87 16pt \"Arial Black\";\n"
"background-color: white;\n"
"border: 2px solid yellow;\n"
"color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 5px solid white;\n"
"background-color: yellow;\n"
"color: black\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"}")
        self.botaoInicio.setObjectName("botaoInicio")
        self.premiacao = QtWidgets.QLabel(parent=self.centralwidget)
        self.premiacao.setGeometry(QtCore.QRect(360, 150, 381, 61))
        self.premiacao.setStyleSheet("QLabel{\n"
"font: 87 32pt \"Arial Black\";\n"
"}")
        self.premiacao.setObjectName("premiacao")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Show do Milhão Finances"))
        self.botaoInicio.setText(_translate("MainWindow", "Início"))
        self.premiacao.setText(_translate("MainWindow", "R$"))
