# Form implementation generated from reading ui file 'c:\Users\barba\Documents\vs\Show do Milhão\segunda pergunta.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 373)
        MainWindow.setMinimumSize(QtCore.QSize(1160, 373))
        MainWindow.setMaximumSize(QtCore.QSize(1160, 373))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\Show do Milhão\\imgs/icone.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -80, 1491, 531))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\Show do Milhão\\imgs/templante pergunta dois.png"))
        self.label.setObjectName("label")
        self.botaoParar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botaoParar.setGeometry(QtCore.QRect(880, 280, 211, 61))
        self.botaoParar.setStyleSheet("QPushButton {\n"
"background-color: rgb(214, 214, 214);\n"
"font: 87 16pt \"Arial Black\";\n"
"color: black;\n"
"border-radius: 15px;\n"
"border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 5px solid red;\n"
"color: red;\n"
"}\n"
"\n"
"QPushButton:clicked {\n"
"\n"
"}")
        self.botaoParar.setObjectName("botaoParar")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 631, 61))
        self.label_2.setStyleSheet("QLabel{\n"
"font: 87 14pt \"Arial Black\";\n"
"color: white;\n"
"}")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 120, 351, 61))
        self.label_3.setStyleSheet("QLabel{\n"
"font: 87 16pt \"Arial Black\";\n"
"color: white;\n"
"}")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 210, 221, 61))
        self.label_4.setStyleSheet("QLabel{\n"
"font: 87 16pt \"Arial Black\";\n"
"color: white;\n"
"}")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.opcaoUm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.opcaoUm.setGeometry(QtCore.QRect(60, 110, 81, 81))
        self.opcaoUm.setStyleSheet("QPushButton {\n"
"background-color: rgb(214, 214, 214);\n"
"font: 87 16pt \"Arial Black\";\n"
"color: black;\n"
"border-radius: 15px;\n"
"border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 5px solid green;\n"
"color: green;\n"
"}\n"
"\n"
"QPushButton:clicked {\n"
"\n"
"}")
        self.opcaoUm.setObjectName("opcaoUm")
        self.opcaoDois = QtWidgets.QPushButton(parent=self.centralwidget)
        self.opcaoDois.setGeometry(QtCore.QRect(60, 200, 81, 81))
        self.opcaoDois.setStyleSheet("QPushButton {\n"
"background-color: rgb(214, 214, 214);\n"
"font: 87 16pt \"Arial Black\";\n"
"color: black;\n"
"border-radius: 15px;\n"
"border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 5px solid green;\n"
"color: green;\n"
"}\n"
"\n"
"QPushButton:clicked {\n"
"\n"
"}")
        self.opcaoDois.setObjectName("opcaoDois")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 290, 101, 61))
        self.label_5.setStyleSheet("QLabel{\n"
"font: 87 14pt \"Arial Black\";\n"
"color: black;\n"
"}")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 290, 121, 61))
        self.label_6.setStyleSheet("QLabel{\n"
"font: 87 14pt \"Arial Black\";\n"
"color: black;\n"
"}")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(560, 290, 131, 61))
        self.label_7.setStyleSheet("QLabel{\n"
"font: 87 14pt \"Arial Black\";\n"
"color: black;\n"
"}")
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Show do Milhão Finances"))
        self.botaoParar.setText(_translate("MainWindow", "Parar"))
        self.label_2.setText(_translate("MainWindow", "Como um analista financeiro, as ações de qual empresa automotiva você compraria para evitar prejuízos?"))
        self.label_3.setText(_translate("MainWindow", "B.Y.D. (Shenzhen)"))
        self.label_4.setText(_translate("MainWindow", "Tesla (Austin)"))
        self.opcaoUm.setText(_translate("MainWindow", "1"))
        self.opcaoDois.setText(_translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "R$5.000"))
        self.label_6.setText(_translate("MainWindow", "R$10.000"))
        self.label_7.setText(_translate("MainWindow", "R$50.000"))
